working_directory = "/home/moamen"

import = [
	"~/.config/alacritty/modus_operandi.toml"
]


shell = "tmux"

[cursor]
vi_mode_style = "Beam"

[font]
size = 14.0

[font.normal]
#family = "Monaspace Radon"
family = "JetbrainsMono NF"


