working_directory = "/home/moamen"

import = [
	"~/.config/alacritty/themes/themes/everforest_light.toml"
]

[cursor]
vi_mode_style = "Beam"

[font]
size = 12.0

[font.normal]
# family = "JetBrainsMono Nerd Font"
family = "CaskaydiaCove Nerd Font"


